version: '3'

services:
  python3:
    build: ./python3
    command: python project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      PYTHONPATH: /code
      LANGUAGE: "${LANGUAGE}"
      TIMEZONE: "${TIMEZONE}"
    ports:
      - "8000:8000"